[package]
name = "duplicate_encode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
counter = "0.5.2"
itertools = "0.10.3"
num-format = "0.4.0"
rayon = "1.5.1"
